FROM ubuntu:16.04

# Instala o CMAKE
RUN apt-get update

# Copia tudo para o container
COPY . /vss-core-rust-ubuntu16
WORKDIR /vss-core-rust-ubuntu16

# Adiciona permissão de execução dos shellscripts
RUN chmod +x /vss-core-rust-ubuntu16/configure.sh

# Executa a instalação na criação dos containers
RUN /vss-core-rust-ubuntu16/configure.sh development

# Script executado no docker run
CMD cargo test